name: CI-Develop

on:
  push:
    branches:
      - 'feature/*'

jobs:
  validar_commit:
    name: Validar palabra clave en commit
    runs-on: ubuntu-latest

    steps:
      - name: Obtener mensaje de commit
        id: commit
        run: |
          echo "Commit message: ${{ github.event.head_commit.message }}"
          echo "::set-output name=commit_message::${{ github.event.head_commit.message }}"

      - name: Validar palabra clave 'Azul'
        if: contains(steps.commit.outputs.commit_message, 'Azul')
        run: echo "El commit contiene la palabra clave 'Azul'."
        
      - name: Finalizar si no contiene 'Azul'
        if: "!contains(steps.commit.outputs.commit_message, 'Azul')"
        run: |
          echo "El commit no contiene la palabra clave 'Azul'. No se har치 la integraci칩n."
          exit 1

  actualizar_con_develop:
    name: Actualizar rama funcionalidad con develop
    runs-on: ubuntu-latest
    needs: validar_commit

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Actualizar rama funcionalidad con develop
        run: |
          git fetch origin
          git checkout ${{ github.ref }}
          git merge origin/develop --no-ff
          git push origin ${{ github.ref }}

  correr_pruebas:
    name: Correr pruebas en rama de funcionalidad
    runs-on: ubuntu-latest
    needs: actualizar_con_develop

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configuraci칩n de entorno de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Instalaci칩n de dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar pruebas
        run: python -m unittest discover -s tests

  fusionar_a_develop:
    name: Fusionar a develop
    runs-on: ubuntu-latest
    needs: correr_pruebas
    if: success()

    steps:
      - name: Checkout de develop y la rama funcionalidad
        uses: actions/checkout@v3

      - name: Configurar Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fusionar la rama funcionalidad a develop
        run: |
          git checkout develop
          git merge ${{ github.ref }} --no-ff
          git push origin develop
